package crypt

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
)

const (
	lockVersion = 2
	lockHeader  = "# generated by envguardian — do not edit\n"
)

// LockFile is the committed lock.toml schema. Each entry is bound to the
// exact public ciphertext bytes as well as the public recipient set.
type LockFile struct {
	Version int         `toml:"version"`
	Files   []LockEntry `toml:"file"`
}

// LockEntry is one configured ciphertext's public integrity state.
type LockEntry struct {
	Ciphertext            string `toml:"ciphertext"`
	RecipientsFingerprint string `toml:"recipients_fingerprint"`
	CiphertextSHA256      string `toml:"ciphertext_sha256"`
}

// LockTarget pairs the configured repository-relative name with its resolved
// filesystem path for verification.
type LockTarget struct {
	Ciphertext string
	Path       string
}

// LockBlobTarget pairs a configured ciphertext name with exact bytes from a
// repository snapshot (for example, Git's index). It lets hooks verify the
// snapshot being committed without consulting a working-tree file.
type LockBlobTarget struct {
	Ciphertext string
	Data       []byte
}

func ciphertextDigest(ciphertext []byte) string {
	sum := sha256.Sum256(ciphertext)
	return hex.EncodeToString(sum[:])
}

func parseLock(data []byte) (*LockFile, error) {
	var lock LockFile
	metadata, err := toml.Decode(string(data), &lock)
	if err != nil {
		return nil, fmt.Errorf("parse TOML: %w", err)
	}
	if undecoded := metadata.Undecoded(); len(undecoded) > 0 {
		return nil, fmt.Errorf("unknown field %q", undecoded[0].String())
	}
	if lock.Version != lockVersion {
		return nil, fmt.Errorf("unsupported lock version %d (want %d)", lock.Version, lockVersion)
	}
	if len(lock.Files) == 0 {
		return nil, errors.New("lock has no [[file]] entries")
	}
	seen := make(map[string]struct{}, len(lock.Files))
	for i := range lock.Files {
		entry := &lock.Files[i]
		entry.Ciphertext = filepath.ToSlash(strings.TrimSpace(entry.Ciphertext))
		if entry.Ciphertext == "" {
			return nil, fmt.Errorf("lock file entry #%d has no ciphertext", i+1)
		}
		if _, exists := seen[entry.Ciphertext]; exists {
			return nil, fmt.Errorf("duplicate lock entry for ciphertext %q", entry.Ciphertext)
		}
		seen[entry.Ciphertext] = struct{}{}
		if !validFingerprint(entry.RecipientsFingerprint) {
			return nil, fmt.Errorf("lock entry %q has a malformed recipients_fingerprint", entry.Ciphertext)
		}
		if !validSHA256(entry.CiphertextSHA256) {
			return nil, fmt.Errorf("lock entry %q has a malformed ciphertext_sha256", entry.Ciphertext)
		}
		entry.CiphertextSHA256 = strings.ToLower(entry.CiphertextSHA256)
	}
	return &lock, nil
}

func loadLock(path string) (*LockFile, error) {
	data, err := os.ReadFile(path) //nolint:gosec // repository lock path
	if err != nil {
		return nil, err
	}
	lock, err := parseLock(data)
	if err != nil {
		return nil, fmt.Errorf("lock file %s is invalid: %w", path, err)
	}
	return lock, nil
}

func validSHA256(value string) bool {
	value = strings.TrimSpace(value)
	if len(value) != sha256.Size*2 {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}

func validFingerprint(value string) bool {
	scheme, digest, ok := strings.Cut(strings.TrimSpace(value), ":")
	return ok && scheme == "v1" && validSHA256(digest)
}

func encodeLock(entries []LockEntry) ([]byte, error) {
	var out strings.Builder
	out.WriteString(lockHeader)
	if err := toml.NewEncoder(&out).Encode(LockFile{Version: lockVersion, Files: entries}); err != nil {
		return nil, fmt.Errorf("encode lock file: %w", err)
	}
	return []byte(out.String()), nil
}

func lockEntryFor(lock *LockFile, ciphertext string) (LockEntry, bool) {
	want := filepath.ToSlash(ciphertext)
	for _, entry := range lock.Files {
		if entry.Ciphertext == want {
			return entry, true
		}
	}
	return LockEntry{}, false
}

// lockMatches reports whether the current lock has exactly the expected entry
// and binds it to both the current ciphertext bytes and recipient fingerprint.
// Invalid or legacy lock files return false so an explicit seal can repair
// them; VerifyLock returns their detailed failure instead.
func lockMatches(lockPath, ciphertextName, fingerprint string, ciphertext []byte) bool {
	lock, err := loadLock(lockPath)
	if err != nil || len(lock.Files) != 1 {
		return false
	}
	entry, ok := lockEntryFor(lock, ciphertextName)
	return ok && entry.RecipientsFingerprint == fingerprint && entry.CiphertextSHA256 == ciphertextDigest(ciphertext)
}

// VerifyLock requires exactly one valid lock entry per configured ciphertext,
// with no extras, and verifies the recipient fingerprint and exact ciphertext
// digest for every entry.
func VerifyLock(lockPath string, targets []LockTarget, wantFingerprint string) error {
	data, err := os.ReadFile(lockPath) //nolint:gosec // repository lock path
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("lock file %s is missing: run `envguardian encrypt` to regenerate it: %w", lockPath, err)
		}
		return fmt.Errorf("read lock file %s: %w", lockPath, err)
	}
	blobs := make([]LockBlobTarget, 0, len(targets))
	for _, target := range targets {
		ciphertext, readErr := os.ReadFile(target.Path) //nolint:gosec // validated managed ciphertext path
		if readErr != nil {
			return fmt.Errorf("read ciphertext %s while verifying lock: %w", target.Ciphertext, readErr)
		}
		blobs = append(blobs, LockBlobTarget{Ciphertext: target.Ciphertext, Data: ciphertext})
	}
	if err := VerifyLockBytes(data, blobs, wantFingerprint); err != nil {
		return fmt.Errorf("lock file %s is invalid: %w", lockPath, err)
	}
	return nil
}

// VerifyLockBytes verifies an exact lock snapshot against exact ciphertext
// snapshots. Ciphertext digests are derivatives of public data and are safe to
// compare; no plaintext derivative is produced.
func VerifyLockBytes(lockData []byte, targets []LockBlobTarget, wantFingerprint string) error {
	lock, err := parseLock(lockData)
	if err != nil {
		return err
	}
	if len(lock.Files) != len(targets) {
		return fmt.Errorf("lock has %d entries, but config has %d ciphertexts", len(lock.Files), len(targets))
	}
	wanted := make(map[string]LockBlobTarget, len(targets))
	for _, target := range targets {
		name := filepath.ToSlash(target.Ciphertext)
		if _, duplicate := wanted[name]; duplicate {
			return fmt.Errorf("configured ciphertext %q appears more than once", name)
		}
		wanted[name] = target
	}
	for _, entry := range lock.Files {
		target, ok := wanted[entry.Ciphertext]
		if !ok {
			return fmt.Errorf("lock contains extra ciphertext entry %q", entry.Ciphertext)
		}
		if entry.RecipientsFingerprint != wantFingerprint {
			return fmt.Errorf("recipient set is out of sync for %s: lock fingerprint differs from recipients.toml", entry.Ciphertext)
		}
		if got := ciphertextDigest(target.Data); got != entry.CiphertextSHA256 {
			return fmt.Errorf("ciphertext %s does not match its lock digest; a write or merge may have been interrupted", entry.Ciphertext)
		}
		delete(wanted, entry.Ciphertext)
	}
	for name := range wanted {
		return fmt.Errorf("lock is missing configured ciphertext %q", name)
	}
	return nil
}
