package crypt

import (
	"fmt"
	"os"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/YehiaGewily/envguardian/internal/atomic"
)

const (
	lockVersion = 1
	lockHeader  = "# generated by envguardian — do not edit\n"
)

// lockContents is the entire lock.toml: only the recipient-set fingerprint (a
// derivative of PUBLIC data) plus a format version. No plaintext derivatives;
// see CONTRIBUTING.md. This prototype is not yet bound to ciphertext bytes.
type lockContents struct {
	Version               int    `toml:"version"`
	RecipientsFingerprint string `toml:"recipients_fingerprint"`
}

// readLockFingerprint returns the recorded fingerprint, or ("", false) if the
// lock is missing, unreadable, or unparseable — all treated as "unknown".
func readLockFingerprint(path string) (string, bool) {
	data, err := os.ReadFile(path) //nolint:gosec // G304: user-configured lock path
	if err != nil {
		return "", false
	}
	var lc lockContents
	if err := toml.Unmarshal(data, &lc); err != nil {
		return "", false
	}
	if lc.RecipientsFingerprint == "" {
		return "", false
	}
	return lc.RecipientsFingerprint, true
}

// writeLock writes lock.toml atomically. Output is deterministic, so rewriting
// an unchanged fingerprint produces identical bytes and no git churn.
func writeLock(path, fingerprint string) error {
	var b strings.Builder
	b.WriteString(lockHeader)
	if err := toml.NewEncoder(&b).Encode(lockContents{Version: lockVersion, RecipientsFingerprint: fingerprint}); err != nil {
		return fmt.Errorf("encode lock file: %w", err)
	}
	return atomic.WriteFile(path, []byte(b.String()), 0o644)
}

// VerifyLock reports whether lock.toml matches the current recipient
// fingerprint. A missing, unparseable, or mismatched lock is an out-of-sync
// error. This checks only the public recipient fingerprint; it does not prove
// which ciphertext bytes were produced for that recipient set.
func VerifyLock(lockPath, wantFingerprint string) error {
	got, ok := readLockFingerprint(lockPath)
	if !ok {
		return fmt.Errorf("lock file %s is missing or unreadable: run `envguardian encrypt` to regenerate it", lockPath)
	}
	if got != wantFingerprint {
		return fmt.Errorf(
			"recipient set is out of sync: %s records a different recipient fingerprint than recipients.toml — "+
				"the committed ciphertext was encrypted to a different set of keys (a merge likely took one side); "+
				"run `envguardian encrypt` to re-encrypt to the current recipients", lockPath)
	}
	return nil
}
